# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d734b10d603a797d4737582b4a900e38f94dfc1f4e5b95096907c65a5c2c118c2b9cb8964747744ea41b9c33aa89bd84d547ddb2694cd5468c6b887ca657a1a4

test:
  secret_key_base: 40b2f5489e272bbc20530b8f4f2f17d71566bc4f980ac6160e0bb27dbfbf0f572248d6ef1b2bc9dd6e4e299cd0aeb5d89b6ae9616afcab26f9cfbdbc280ef182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
